# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/dustinsand/pre-commit-jvm
    rev: v0.11.0
    hooks:
      - id: detekt
